name: marco_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - astropy=6.1.3=py311h9f3472d_1
  - astropy-iers-data=0.2024.9.12.13.29.57=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_2
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cfitsio=4.4.1=hf8ad068_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py311hd18a35c_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py311hfdbb021_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fast-pt=3.1.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - fonttools=4.53.1=py311h9ecbd09_1
  - freetype=2.12.1=h267a509_2
  - gcc_impl_linux-64=13.3.0=hfea6d02_1
  - gcc_linux-64=13.3.0=hc28eda2_2
  - gfortran_impl_linux-64=13.3.0=h10434e7_1
  - gfortran_linux-64=13.3.0=hb919d3a_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_2
  - gsl=2.7=he838d99_0
  - healpy=1.17.3=py311hc30af9e_2
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_16
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=23_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=23_linux64_openblas
  - libcurl=8.10.0=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=13.3.0=h84ea5a7_101
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=23_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.44=hadc24fc_0
  - libsanitizer=13.3.0=heb74ff8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.6.0=h46a8edc_4
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311h9ecbd09_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyerfa=2.0.1.4=py311h9f3472d_2
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - python=3.11.10=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pyyaml=6.0.2=py311h9ecbd09_1
  - pyzmq=26.2.0=py311h7deb3e3_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - scipy=1.14.1=py311he1f765f_0
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h4a8ded7_16
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py311h9ecbd09_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.1=pyhd8ed1ab_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - attrs==25.1.0
      - autograd==1.8.0
      - babel==2.17.0
      - basemap==2.0.0
      - basemap-data
      - beautifulsoup4==4.12.3
      - cachetools==5.5.2
      - camb==1.5.9
      - chainconsumer==1.1.3
      - charset-normalizer==3.4.0
      - classy==3.2.5
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - colossus==1.3.6
      - corner==2.2.3
      - cosmology==2022.10.9
      - coverage==7.6.10
      - coveralls==4.0.1
      - cython==3.0.11
      - dill==0.4.0
      - distlib==0.3.9
      - dm-tree==0.1.9
      - docopt==0.6.2
      - docutils==0.21.2
      - ducc0==0.36.0
      - emcee==3.1.6
      - ephem==4.2
      - euclidemu2==0.0.0
      - extension-helpers==1.2.0
      - fastjsonschema==2.21.2
      - fgivenx==2.4.2
      - filelock==3.17.0
      - flatbuffers==25.1.24
      - flt==2025.1
      - frogress==0.10.1
      - frozenlist==1.5.0
      - gast==0.4.0
      - gaussiancl==2023.1
      - getdist==1.5.4
      - git+https://github.com/glass-dev/glass.git@gowerst
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.69.1
      - grpcio==1.70.0
      - h5py==3.12.1
      - halotools==0.9.3
      - healpix==2024.2
      - healsparse==1.11.1
      - hpgeom==1.4.0
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - ipython-genutils==0.2.0
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.8.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.45.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.8.4
      - mcfit==0.0.22
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpi4py==4.0.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.18
      - namex==0.0.8
      - networkx==3.4.2
      - numba==0.62.0
      - numexpr==2.10.2
      - numpy==2.1.1
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opt-einsum==3.4.0
      - optree==0.14.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pathlib==1.0.1
      - pathos==0.3.4
      - patsy==1.0.1
      - pillow==11.1.0
      - pixell==0.28.0
      - pluggy==1.5.0
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.21.1
      - propcache==0.3.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - py-spy==0.4.0
      - pyaml==25.7.0
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyccl==3.2.1
      - pycparser==2.23
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pymanopt==0.2.5
      - pyproj==3.6.1
      - pyro-api==0.1.2
      - pyshp==2.3.1
      - pytest==8.3.4
      - pytest-cov==6.0.0
      - pytz==2024.2
      - ray==2.43.0
      - referencing==0.36.2
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.23.1
      - rsa==4.9
      - sacc==1.0.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.0
      - send2trash==1.8.3
      - skymap==0.2.0
      - skyproj==2.1.1
      - smart-open==7.1.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.4
      - swig==4.2.1.post0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.1.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.25.0
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2025.6.11
      - tinycss2==1.4.0
      - tjpcov==0.5.1
      - toolz==1.0.0
      - transformcl==2022.8.9
      - treecorr==5.0.2
      - triton==3.1.0
      - tzdata==2024.2
      - unyt==3.0.3
      - urllib3==2.2.3
      - virtualenv==20.29.3
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.18.3
      - zict==3.0.0
prefix: /global/homes/m/mgatti/.conda/envs/pyccl_env